"use strict";

const W=1280,H=720,TAU=Math.PI*2;
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d");
ctx.imageSmoothingEnabled=false;
const ui={start:document.getElementById("start-screen"),upgrade:document.getElementById("upgrade-screen"),pause:document.getElementById("pause-screen"),pauseButton:document.getElementById("pause-button"),over:document.getElementById("game-over-screen"),cards:document.getElementById("upgrade-cards"),stats:document.getElementById("final-stats"),record:document.getElementById("new-record"),healthFill:document.getElementById("hud-health-fill"),healthText:document.getElementById("hud-health-text"),kills:document.getElementById("hud-kills"),weapon:document.getElementById("hud-weapon"),next:document.getElementById("hud-next"),time:document.getElementById("hud-time")};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const rand=(a,b)=>a+Math.random()*(b-a);
const hit=(a,b)=>a.x-a.w/2<b.x+b.w/2&&a.x+a.w/2>b.x-b.w/2&&a.y-a.h/2<b.y+b.h/2&&a.y+a.h/2>b.y-b.h/2;
const length=(x,y)=>Math.hypot(x,y)||1;
const formatTime=s=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(Math.floor(s%60)).padStart(2,"0")}`;

const music=new Audio("music.mp3");music.loop=true;music.volume=.34;music.preload="auto";
const zombieEffect=new Audio("effect.mp3");zombieEffect.volume=.38;zombieEffect.preload="auto";
let audioCtx=null;
function startAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();music.currentTime=0;music.play().catch(()=>{})}
function gunSound(level){if(!audioCtx||audioCtx.state!=="running")return;const family=Math.floor(level/2),profiles=[110,82,150,138,72,62],freq=profiles[family]||62,now=audioCtx.currentTime,osc=audioCtx.createOscillator(),gain=audioCtx.createGain(),filter=audioCtx.createBiquadFilter();osc.type=family>=4?"sawtooth":"square";osc.frequency.setValueAtTime(freq,now);osc.frequency.exponentialRampToValueAtTime(Math.max(38,freq*.42),now+.045);filter.type="lowpass";filter.frequency.value=family===1?520:family>=4?760:1100;gain.gain.setValueAtTime(family===1?.315:.162,now);gain.gain.exponentialRampToValueAtTime(.0001,now+(family===1?.1:.055));osc.connect(filter).connect(gain).connect(audioCtx.destination);osc.start(now);osc.stop(now+(family===1?.11:.06))}

const weaponKillGoals=[50,65,80,100,125,150,180,215,255,300,350];
const upgradeKillSteps=[20,25,30,35,40,45,50,55,60,65,70,75];

const weapons=[
 {name:"ПИСТОЛЕТ",rate:2,damage:10,count:1,spread:0,pierce:0,speed:620,range:650},
 {name:"ДВОЙНОЙ ПИСТОЛЕТ",rate:2.15,damage:10,count:2,spread:.09,pierce:0,speed:640,range:650},
 {name:"ДРОБОВИК",rate:2.05,damage:15,count:6,spread:.3,pierce:0,speed:590,range:390},
 {name:"ДВОЙНОЙ ДРОБОВИК",rate:1.65,damage:15,count:12,spread:.42,pierce:0,speed:600,range:410},
 {name:"ПИСТОЛЕТ-ПУЛЕМЁТ",rate:6,damage:7,count:1,spread:.09,pierce:0,speed:670,range:620},
 {name:"ДВОЙНОЙ ПИСТОЛЕТ-ПУЛЕМЁТ",rate:5.5,damage:7,count:2,spread:.13,pierce:0,speed:680,range:630},
 {name:"АВТОМАТ ПОРКА",rate:5,damage:15,count:1,spread:.045,pierce:0,speed:720,range:700},
 {name:"ДВОЙНОЙ АВТОМАТ ПОРКА",rate:4.6,damage:15,count:2,spread:.075,pierce:0,speed:730,range:710},
 {name:"ТЯЖЁЛЫЙ АВТОМАТ",rate:4,damage:24,count:1,spread:.035,pierce:1,speed:760,range:760},
 {name:"ДВОЙНОЙ ТЯЖЁЛЫЙ АВТОМАТ",rate:3.7,damage:24,count:2,spread:.065,pierce:1,speed:770,range:770},
 {name:"ДАБАЛАТОРНАЯ ПУШКА",rate:6.5,damage:26,count:3,spread:.14,pierce:2,speed:820,range:820},
 {name:"ДВОЙНАЯ ДАБАЛАТОРНАЯ ПУШКА",rate:6,damage:26,count:6,spread:.22,pierce:2,speed:840,range:840}
];
const enemyTypes={
 normal:{w:24,h:42,hp:30,speed:76,damage:11,body:"#747b7d",head:"#61b955",score:1},
 fast:{w:20,h:33,hp:28,speed:138,damage:9,body:"#a7acad",head:"#73ff69",score:1},
 fat:{w:48,h:55,hp:140,speed:49,damage:23,body:"#4b5254",head:"#347b39",score:1},
 acid:{w:29,h:43,hp:45,speed:82,damage:20,body:"#5b3a72",head:"#b14cff",score:1},
 explosive:{w:30,h:43,hp:40,speed:72,damage:14,body:"#5d665f",head:"#85b875",score:1},
 boss:{w:144,h:165,hp:1800,speed:34,damage:20,clubDamage:38,body:"#343b3d",head:"#234f29",score:1}
};
const zombieShirts=["#6c7475","#79534a","#526b61","#6a6075","#747047","#455f70","#8a8171"];
const zombiePants=["#263d55","#33475b","#3d4144","#4b463e","#2f3840","#514f49"];
const zombieStains=["#4a2625","#3d3823","#283b2c"];
const upgradePool=[
 {name:"УРОН",desc:"+20% к урону",apply:p=>p.damageMult*=1.2},
 {name:"СКОРОСТРЕЛЬНОСТЬ",desc:"+15% к скорости стрельбы",apply:p=>p.rateMult*=1.15},
 {name:"СКОРОСТЬ ПОРКА",desc:"+10% к скорости движения",apply:p=>p.speed*=1.1},
 {name:"ЗДОРОВЬЕ",desc:"+20 макс. HP и восстановить 20",apply:p=>{p.maxHp+=20;p.hp=Math.min(p.maxHp,p.hp+20)}},
 {name:"БРОНЯ",desc:"−10% входящего урона",apply:p=>p.armor=1-(1-p.armor)*.9},
 {name:"ПРОБИВАНИЕ",desc:"Пули пробивают ещё 1 зондби",apply:p=>p.bonusPierce++},
 {name:"ДОП. ПУЛЯ",desc:"+1 пуля за выстрел",apply:p=>p.bonusBullets++},
 {name:"РЕГЕНЕРАЦИЯ",desc:"+1.5 HP каждые 5 секунд",apply:p=>p.regen+=.3}
];

class Particle{constructor(x,y,color){this.x=x;this.y=y;this.vx=rand(-110,110);this.vy=rand(-110,110);this.life=rand(.25,.55);this.max=this.life;this.color=color;this.size=rand(3,7)}update(dt){this.life-=dt;this.x+=this.vx*dt;this.y+=this.vy*dt;this.vx*=.96;this.vy*=.96}draw(){ctx.globalAlpha=clamp(this.life/this.max,0,1);ctx.fillStyle=this.color;ctx.fillRect(this.x,this.y,this.size,this.size);ctx.globalAlpha=1}}
class Bullet{constructor(x,y,a,weapon,p){this.x=x;this.y=y;this.w=9;this.h=4;this.vx=Math.cos(a)*weapon.speed;this.vy=Math.sin(a)*weapon.speed;this.damage=weapon.damage*p.damageMult;this.pierce=weapon.pierce+p.bonusPierce;this.life=weapon.range/weapon.speed;this.hitSet=new Set();this.angle=a}update(dt){this.x+=this.vx*dt;this.y+=this.vy*dt;this.life-=dt}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.angle);ctx.fillStyle="#fff4a8";ctx.fillRect(-6,-2,12,4);ctx.restore()}}
class AcidShot{constructor(x,y,a,color="#b14cff"){this.x=x;this.y=y;this.w=18;this.h=18;this.vx=Math.cos(a)*145;this.vy=Math.sin(a)*145;this.life=7;this.angle=a;this.spin=rand(-5,5);this.color=color}update(dt){this.x+=this.vx*dt;this.y+=this.vy*dt;this.life-=dt;this.angle+=this.spin*dt}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.angle);ctx.fillStyle=this.color;ctx.fillRect(-8,-6,16,12);ctx.fillStyle="#e2a5ff";ctx.fillRect(-4,-9,8,18);ctx.fillStyle="#59246f";ctx.fillRect(-2,-3,7,6);ctx.restore()}}
class Medkit{constructor(x,y,big=false){this.x=x;this.y=y;this.big=big;this.w=big?38:29;this.h=big?38:29;this.life=28;this.pulse=rand(0,TAU);this.dead=false}update(dt){this.life-=dt;this.pulse+=dt*4}draw(){const s=1+Math.sin(this.pulse)*.06;ctx.save();ctx.translate(this.x,this.y);ctx.scale(s,s);ctx.fillStyle=this.big?"#f3f0df":"#dedbd0";ctx.fillRect(-this.w/2,-this.h/2,this.w,this.h);ctx.strokeStyle=this.big?"#ffdc62":"#979d99";ctx.lineWidth=this.big?4:2;ctx.strokeRect(-this.w/2,-this.h/2,this.w,this.h);ctx.fillStyle="#d93636";ctx.fillRect(-this.w*.12,-this.h*.35,this.w*.24,this.h*.7);ctx.fillRect(-this.w*.35,-this.h*.12,this.w*.7,this.h*.24);ctx.restore()}}
class Barrel{constructor(x,y){this.x=x;this.y=y;this.w=34;this.h=45;this.hp=35;this.life=45;this.dead=false;this.isBarrel=true}update(dt){this.life-=dt}draw(){ctx.save();ctx.translate(Math.round(this.x),Math.round(this.y));ctx.fillStyle="#8e2522";ctx.fillRect(-17,-21,34,42);ctx.fillStyle="#c63c32";ctx.fillRect(-14,-18,28,36);ctx.fillStyle="#242829";ctx.fillRect(-17,-15,34,4);ctx.fillRect(-17,11,34,4);ctx.fillStyle="#f2b544";ctx.fillRect(-5,-8,10,16);ctx.fillStyle="#2a2520";ctx.fillRect(-2,-13,4,26);ctx.restore()}}
class BonusPickup{
 constructor(type,x,y){this.type=type;this.x=x;this.y=y;this.w=42;this.h=42;this.life=32;this.pulse=rand(0,TAU);this.dead=false}
 update(dt){this.life-=dt;this.pulse+=dt*4}
 draw(){const s=1+Math.sin(this.pulse)*.08;ctx.save();ctx.translate(this.x,this.y);ctx.scale(s,s);ctx.fillStyle="rgba(0,0,0,.35)";ctx.fillRect(-23,18,46,7);if(this.type==="shield"){ctx.strokeStyle="#67d7ff";ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,18,0,TAU);ctx.stroke();ctx.fillStyle="rgba(103,215,255,.24)";ctx.fillRect(-12,-12,24,24);ctx.fillStyle="#d9f8ff";ctx.fillRect(-3,-14,6,28);ctx.fillRect(-12,-3,24,6)}else{ctx.fillStyle="#ff3c35";ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?8:19;i?ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r):ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.fillStyle="#ffbd35";ctx.fillRect(-4,-5,8,10)}ctx.restore()}
}
class FlameParticle{
 constructor(x,y,a){this.x=x;this.y=y;this.a=a+rand(-.16,.16);this.speed=rand(360,520);this.vx=Math.cos(this.a)*this.speed;this.vy=Math.sin(this.a)*this.speed;this.life=rand(.38,.62);this.max=this.life;this.w=this.h=30;this.dead=false}
 update(dt){this.life-=dt;this.x+=this.vx*dt;this.y+=this.vy*dt;this.vx*=.975;this.vy*=.975;this.w=this.h=24+32*(1-this.life/this.max)}
 draw(){const a=clamp(this.life/this.max,0,1);ctx.save();ctx.translate(this.x,this.y);ctx.globalAlpha=a;ctx.fillStyle="#c9231f";ctx.fillRect(-this.w*.5,-this.h*.5,this.w,this.h);ctx.fillStyle="#ff6828";ctx.fillRect(-this.w*.34,-this.h*.34,this.w*.68,this.h*.68);ctx.fillStyle="#ffd35a";ctx.fillRect(-this.w*.16,-this.h*.16,this.w*.32,this.h*.32);ctx.restore()}
}
class Enemy{
 constructor(type,x,y,id,hpScale=1){Object.assign(this,enemyTypes[type]);this.type=type;this.x=x;this.y=y;this.id=id;this.hp=Math.ceil(this.hp*hpScale);this.maxHp=this.hp;this.flash=0;this.dead=false;this.fuse=-1;this.clubAngle=rand(0,TAU);this.walk=rand(0,TAU);this.shirt=zombieShirts[Math.floor(rand(0,zombieShirts.length))];this.pants=zombiePants[Math.floor(rand(0,zombiePants.length))];this.stain=zombieStains[Math.floor(rand(0,zombieStains.length))];this.canSpit=type==="acid";this.spitCd=this.canSpit?rand(1.2,3.8):999}
 update(dt,g){
  let dx=g.player.x-this.x,dy=g.player.y-this.y,l=length(dx,dy);
  if(this.type==="explosive"&&l<105&&this.fuse<0)this.fuse=1.05;
  if(this.fuse>=0){this.fuse-=dt;if(this.fuse<=0){g.explode(this);return}}
  if(this.type==="boss"){
   this.clubAngle+=dt*2.35;
   const cx=this.x+Math.cos(this.clubAngle)*102,cy=this.y+Math.sin(this.clubAngle)*102;
   if(Math.hypot(g.player.x-cx,g.player.y-cy)<42)g.player.hurt(this.clubDamage,g);
  }
  if(this.canSpit){this.spitCd-=dt;if(this.spitCd<=0&&l>150&&l<620){g.acidShots.push(new AcidShot(this.x,this.y,Math.atan2(dy,dx),this.head));this.spitCd=rand(4.5,7.5)}}
  const slow=this.fuse>=0?.28:1,vx=dx/l*this.speed*slow,vy=dy/l*this.speed*slow;this.walk+=dt*this.speed*.09;
  const next={x:this.x+vx*dt,y:this.y+vy*dt,w:this.w,h:this.h};
  for(const o of g.obstacles){if(hit(next,o)){const tryX={x:this.x+vx*dt,y:this.y,w:this.w,h:this.h};const tryY={x:this.x,y:this.y+vy*dt,w:this.w,h:this.h};if(!hit(tryX,o))this.x=tryX.x;else if(!hit(tryY,o))this.y=tryY.y;else{const side=(this.id%2?1:-1);this.x+=-dy/l*this.speed*.7*side*dt;this.y+=dx/l*this.speed*.7*side*dt}this.flash=Math.max(0,this.flash-dt);return}}
  this.x=next.x;this.y=next.y;this.flash=Math.max(0,this.flash-dt)
 }
 draw(){
  ctx.save();ctx.translate(Math.round(this.x),Math.round(this.y));const step=Math.sin(this.walk)*2;ctx.fillStyle="rgba(0,0,0,.28)";ctx.fillRect(-this.w*.48,this.h*.42,this.w*.96,5);
  if(this.type==="boss"){
   ctx.save();ctx.rotate(this.clubAngle);ctx.fillStyle="#6b4a2b";ctx.fillRect(25,-8,92,16);ctx.fillStyle="#292523";ctx.fillRect(99,-19,36,38);ctx.restore()
  }
  const fuseBlink=this.type==="explosive"&&this.fuse>=0&&Math.floor(this.fuse*12)%2===0;
  if(this.flash>0||fuseBlink){ctx.fillStyle=fuseBlink?"#fff6b0":"#fff";ctx.fillRect(-this.w/2,-this.h/2,this.w,this.h)}else if(this.type==="normal"){ctx.fillStyle=this.pants;ctx.fillRect(-7,9,5,22-step);ctx.fillRect(2,9,5,22+step);ctx.fillStyle="#171a1b";ctx.fillRect(-8,29-step,7,4);ctx.fillRect(1,29+step,7,4);ctx.fillStyle=this.shirt;ctx.fillRect(-7,-5,14,18);ctx.fillStyle=this.body;ctx.fillRect(-12,-3+step,5,18);ctx.fillRect(7,-3-step,5,18);ctx.fillStyle="#96a193";ctx.fillRect(-12,12+step,5,4);ctx.fillRect(7,12-step,5,4);ctx.fillStyle=this.stain;ctx.fillRect(-5,-2,5,4);ctx.fillRect(2,5,4,3);ctx.fillStyle=this.head;ctx.fillRect(-9,-20,18,15);ctx.fillStyle="#172018";ctx.fillRect(-5,-15,3,3);ctx.fillRect(3,-15,3,3);ctx.fillStyle="#39443b";ctx.fillRect(-3,-9,6,2);ctx.fillStyle=this.stain;ctx.fillRect(4,-7,4,3)}else{ctx.fillStyle=this.body;ctx.fillRect(-this.w/2,-this.h/2+this.h*.3,this.w,this.h*.7);ctx.fillStyle=this.head;ctx.fillRect(-this.w*.42,-this.h/2,this.w*.84,this.h*.34);ctx.fillStyle="#172018";const eye=Math.max(3,this.w*.08);ctx.fillRect(-this.w*.22,-this.h*.36,eye,eye);ctx.fillRect(this.w*.12,-this.h*.36,eye,eye)}
  if(this.type==="acid"){ctx.fillStyle="#d889ff";ctx.fillRect(-this.w*.38,this.h*.33,this.w*.76,4)}
  if(this.type==="explosive"){ctx.fillStyle="#d83a32";ctx.fillRect(-this.w*.5,-2,this.w,6);ctx.fillStyle="#ff9a3c";ctx.fillRect(-3,-5,6,12)}
  if(this.type==="boss"){ctx.fillStyle="#7c1717";ctx.fillRect(-this.w/2,-this.h/2-15,this.w,9);ctx.fillStyle="#73ff69";ctx.fillRect(-this.w/2,-this.h/2-15,this.w*clamp(this.hp/this.maxHp,0,1),9)}
  ctx.restore()
 }
}
class Player{constructor(){this.x=W/2;this.y=H/2+50;this.vx=0;this.vy=0;this.w=24;this.h=38;this.maxHp=100;this.hp=100;this.speed=220;this.damageMult=1;this.rateMult=1;this.armor=0;this.bonusPierce=0;this.bonusBullets=0;this.regen=0;this.invuln=0;this.fireCd=0;this.aim=-Math.PI/2}update(dt,g){let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0)+joystick.x,dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0)+joystick.y,l=Math.hypot(dx,dy);if(l>1){dx/=l;dy/=l}const response=l>.01?18:26,smooth=1-Math.exp(-response*dt);this.vx+=(dx*this.speed-this.vx)*smooth;this.vy+=(dy*this.speed-this.vy)*smooth;if(Math.abs(this.vx)<.15)this.vx=0;if(Math.abs(this.vy)<.15)this.vy=0;const ox=this.x,oy=this.y,minX=this.w/2+8,maxX=W-this.w/2-8,minY=112+this.h/2,maxY=H-this.h/2-8;this.x=clamp(this.x+this.vx*dt,minX,maxX);this.y=clamp(this.y+this.vy*dt,minY,maxY);for(const o of g.obstacles)if(hit(this,o)){this.x=ox;this.y=oy;this.vx=0;this.vy=0}this.x=clamp(this.x,minX,maxX);this.y=clamp(this.y,minY,maxY);if(this.x===minX||this.x===maxX)this.vx=0;if(this.y===minY||this.y===maxY)this.vy=0;this.invuln=Math.max(0,this.invuln-dt);this.fireCd-=dt;if(this.regen)this.hp=Math.min(this.maxHp,this.hp+this.regen*dt);let target=null,best=500*500;for(const e of [...g.enemies,...g.barrels]){const d=(e.x-this.x)**2+(e.y-this.y)**2;if(!e.dead&&d<best){best=d;target=e}}if(target){this.aim=Math.atan2(target.y-this.y,target.x-this.x);const weapon=weapons[g.weaponLevel];if(this.fireCd<=0){g.fire(weapon);this.fireCd=1/(weapon.rate*this.rateMult)}}}hurt(amount,g){if(this.invuln>0)return;this.hp-=amount*.85*(1-this.armor);this.invuln=.5;g.hitFlash=.28;g.shake=Math.min(7,amount*.22);for(let i=0;i<5;i++)g.particles.push(new Particle(this.x,this.y,"#ff4e45"));if(this.hp<=0)g.end()}draw(g){ctx.save();ctx.translate(Math.round(this.x),Math.round(this.y));ctx.globalAlpha=this.invuln>0&&Math.floor(this.invuln*18)%2?.35:1;ctx.fillStyle="rgba(0,0,0,.42)";ctx.fillRect(-15,15,30,7);ctx.strokeStyle="#d8e1dd";ctx.lineWidth=2;ctx.strokeRect(-13,-24,26,44);ctx.fillStyle="#090b0c";ctx.fillRect(-12,-10,24,29);ctx.fillStyle="#ece9df";ctx.fillRect(-3,-8,6,10);ctx.fillStyle="#d33b35";ctx.fillRect(-2,1,4,10);ctx.fillStyle="#bd8a65";ctx.fillRect(-9,-23,18,14);ctx.fillStyle="#171514";ctx.fillRect(-9,-23,18,4);if(this.invuln>0){ctx.strokeStyle="rgba(115,255,105,.75)";ctx.strokeRect(-17,-28,34,52)}ctx.rotate(this.aim);ctx.fillStyle="#17191a";ctx.fillRect(7,-3,22,6);ctx.fillStyle="#858d8e";ctx.fillRect(23,-2,10,4);ctx.restore()}}

Player.prototype.draw=function(g){
 const moving=Math.hypot(this.vx,this.vy)>.5,walk=moving?Math.sin(performance.now()*.014)*3:0;
 ctx.save();ctx.translate(Math.round(this.x),Math.round(this.y));ctx.globalAlpha=this.invuln>0&&Math.floor(this.invuln*18)%2?.35:1;
 ctx.fillStyle="rgba(0,0,0,.42)";ctx.fillRect(-15,17,30,7);
 ctx.fillStyle="#111416";ctx.fillRect(-9,5-walk,7,17);ctx.fillRect(2,5+walk,7,17);ctx.fillStyle="#080a0b";ctx.fillRect(-10,19-walk,9,4);ctx.fillRect(1,19+walk,9,4);
 ctx.fillStyle="#111416";ctx.fillRect(-10,-9,20,20);ctx.fillStyle="#e7e5df";ctx.fillRect(-3,-8,6,10);ctx.fillStyle="#7e2524";ctx.fillRect(-2,1,4,10);
 ctx.fillStyle="#111416";ctx.fillRect(-15,-7+walk,5,17);ctx.fillRect(10,-7-walk,5,17);ctx.fillStyle="#bd8a65";ctx.fillRect(-15,8+walk,5,4);ctx.fillRect(10,8-walk,5,4);
 ctx.fillStyle="#bd8a65";ctx.fillRect(-9,-25,18,16);ctx.fillStyle="#6b3527";ctx.fillRect(-11,-27,22,6);ctx.fillRect(-11,-23,5,15);ctx.fillRect(6,-23,5,15);ctx.fillRect(-7,-11,14,5);
 ctx.fillStyle="#f0eee7";ctx.fillRect(-5,-20,3,3);ctx.fillRect(3,-20,3,3);ctx.fillStyle="#17110f";ctx.fillRect(-4,-19,2,2);ctx.fillRect(3,-19,2,2);ctx.fillStyle="#8a4935";ctx.fillRect(-5,-14,10,5);ctx.fillStyle="#4d251d";ctx.fillRect(-3,-14,6,2);
 if(this.invuln>0){ctx.strokeStyle="rgba(115,255,105,.75)";ctx.lineWidth=2;ctx.strokeRect(-17,-29,34,54)}
 ctx.rotate(this.aim);ctx.fillStyle="#17191a";ctx.fillRect(7,-3,22,6);ctx.fillStyle="#858d8e";ctx.fillRect(23,-2,10,4);ctx.restore()
};

class Game{
 constructor(){this.state="menu";this.bestKills=Number(localStorage.getItem("porkBestKills")||0);this.bestTime=Number(localStorage.getItem("porkBestTime")||0);this.last=performance.now();this.setupArena();requestAnimationFrame(t=>this.loop(t))}
 setupArena(){this.cracks=Array.from({length:30},()=>({x:rand(0,W),y:rand(120,H),a:rand(0,TAU),l:rand(12,45)}));this.debris=Array.from({length:28},()=>({x:rand(0,W),y:rand(120,H),w:rand(3,12),h:rand(3,8),c:Math.random()<.2?"#9d433c":"#33393b"}));this.obstacles=[{x:252,y:282,w:128,h:55,a:-.13,c:"#6d3635"},{x:1010,y:312,w:120,h:53,a:.1,c:"#354d5f"},{x:830,y:590,w:132,h:56,a:-.08,c:"#70673d"},{x:460,y:555,w:110,h:50,a:.06,c:"#3d5c49"}]}
 start(){this.player=new Player();this.enemies=[];this.bullets=[];this.acidShots=[];this.medkits=[];this.barrels=[];this.particles=[];this.kills=0;this.weaponKills=0;this.time=0;this.spawnCd=1.6;this.medkitCd=rand(24,38);this.enemyId=0;this.weaponLevel=0;this.nextUpgrade=upgradeKillSteps[0];this.nextZombieEffect=rand(7,13);this.nextBoss=180;this.bossWave=1;this.banner=0;this.bannerTitle="";this.bannerText="";this.shake=0;this.hitFlash=0;this.state="play";hideAll();ui.pauseButton.hidden=false;resetJoystick();startAudio()}
 fire(w){const total=w.count+this.player.bonusBullets,earlyBoost=1+.2*clamp(1-this.time/120,0,1),difficultyBoost=1+.05*Math.max(0,(this.time-120)/60);for(let i=0;i<total;i++){const pos=total===1?0:(i/(total-1)-.5);const a=this.player.aim+pos*w.spread+rand(-w.spread*.08,w.spread*.08),shot={...w,damage:w.damage*earlyBoost*difficultyBoost};this.bullets.push(new Bullet(this.player.x+Math.cos(a)*30,this.player.y+Math.sin(a)*30,a,shot,this.player))}gunSound(this.weaponLevel);for(let i=0;i<2;i++)this.particles.push(new Particle(this.player.x+Math.cos(this.player.aim)*32,this.player.y+Math.sin(this.player.aim)*32,"#fff4a8"))}
 hpScale(){if(this.time<120)return .5+.5*(this.time/120);return 1+.2*((this.time-120)/60)}
 spawn(forcedType=null){let side=Math.floor(Math.random()*4),x,y,margin=forcedType==="boss"?100:28;if(side===0){x=rand(20,W-20);y=105-margin}else if(side===1){x=W+margin;y=rand(130,H-20)}else if(side===2){x=rand(20,W-20);y=H+margin}else{x=-margin;y=rand(130,H-20)}let type=forcedType||"normal";if(!forcedType&&this.time>=60){const r=Math.random(),explosive=this.time>=180?Math.min(.18,.075+(this.time-180)/1600):0,acid=this.time>=120?Math.min(.18,.08+(this.time-120)/1800):0,fat=this.time>=120?Math.min(.17,.10+(this.time-120)/1800):0,fast=Math.min(.28,.20+(this.time-60)/1800);if(r<explosive)type="explosive";else if(r<explosive+acid)type="acid";else if(r<explosive+acid+fat)type="fat";else if(r<explosive+acid+fat+fast)type="fast"}this.enemies.push(new Enemy(type,x,y,this.enemyId++,this.hpScale()))}
 explode(e){if(e.dead)return;e.dead=true;const radius=220,push=rand(155,215),dx=this.player.x-e.x,dy=this.player.y-e.y,d=length(dx,dy);if(d<radius){this.player.hurt(50,this);this.player.x=clamp(this.player.x+dx/d*push,this.player.w/2+8,W-this.player.w/2-8);this.player.y=clamp(this.player.y+dy/d*push,112+this.player.h/2,H-this.player.h/2-8);this.player.vx=dx/d*520;this.player.vy=dy/d*520}for(const other of this.enemies){if(other===e||other.dead)continue;const ox=other.x-e.x,oy=other.y-e.y,od=length(ox,oy);if(od<275){other.x+=ox/od*push;other.y+=oy/od*push}}for(let i=0;i<144;i++){const p=new Particle(e.x,e.y,i%5?i%2?"#ff6a2b":"#ffb23d":"#f4ff94");p.vx*=3.1;p.vy*=3.1;p.size*=1.8;p.life*=2;p.max=p.life;this.particles.push(p)}this.shake=18}
 resetWeaponUpgrades(){this.player.damageMult=1;this.player.rateMult=1;this.player.bonusPierce=0;this.player.bonusBullets=0}
 spawnMedkit(){for(let tries=0;tries<30;tries++){const big=Math.random()<.22,x=rand(60,W-60),y=rand(145,H-55),candidate={x,y,w:big?38:29,h:big?38:29};if(this.obstacles.some(o=>hit(candidate,o))||Math.hypot(x-this.player.x,y-this.player.y)<150)continue;this.medkits.push(new Medkit(x,y,big));return}}
 spawnBarrel(){for(let tries=0;tries<30;tries++){const x=rand(60,W-60),y=rand(145,H-55),candidate={x,y,w:34,h:45};if(this.obstacles.some(o=>hit(candidate,o))||Math.hypot(x-this.player.x,y-this.player.y)<170||this.barrels.some(b=>hit(candidate,b)))continue;this.barrels.push(new Barrel(x,y));return}}
 explodeBarrel(barrel){if(barrel.dead)return;barrel.dead=true;const radius=255;for(const e of this.enemies){if(e.dead)continue;const d=Math.hypot(e.x-barrel.x,e.y-barrel.y);if(d<radius){e.hp-=260*(1-d/radius*.45);const push=110*(1-d/radius);e.x+=(e.x-barrel.x)/(d||1)*push;e.y+=(e.y-barrel.y)/(d||1)*push;if(e.hp<=0)this.kill(e)}}for(const other of this.barrels){if(other!==barrel&&!other.dead&&Math.hypot(other.x-barrel.x,other.y-barrel.y)<radius*.72)this.explodeBarrel(other)}for(let i=0;i<140;i++){const p=new Particle(barrel.x,barrel.y,i%4?"#ff9a32":"#fff0a0");p.vx*=3.4;p.vy*=3.4;p.size*=1.8;p.life*=2.1;p.max=p.life;this.particles.push(p)}this.shake=16}
 kill(e){if(e.dead)return;e.dead=true;this.kills++;this.weaponKills++;for(let i=0;i<(e.type==="boss"?28:6);i++)this.particles.push(new Particle(e.x,e.y,i%2?e.head:e.body));const goal=weaponKillGoals[this.weaponLevel];if(this.weaponLevel<weapons.length-1&&this.weaponKills>=goal){this.weaponLevel++;this.weaponKills=0;this.resetWeaponUpgrades();this.nextUpgrade=upgradeKillSteps[this.weaponLevel];this.banner=1.8;this.bannerTitle="НОВОЕ ОРУЖИЕ — БОНУСЫ СБРОШЕНЫ";this.bannerText=weapons[this.weaponLevel].name;return}if(this.weaponKills>=this.nextUpgrade){this.nextUpgrade+=upgradeKillSteps[this.weaponLevel];this.showUpgrades()}}
 showUpgrades(){this.state="upgrade";ui.pauseButton.hidden=true;resetJoystick();ui.cards.textContent="";const choices=[...upgradePool].sort(()=>Math.random()-.5).slice(0,3);for(const u of choices){const b=document.createElement("button");b.className="card";b.innerHTML=`<b>${u.name}</b><span>${u.desc}</span>`;b.onclick=()=>{u.apply(this.player);ui.upgrade.classList.remove("active");ui.pauseButton.hidden=false;this.state="play";this.last=performance.now()};ui.cards.appendChild(b)}ui.upgrade.classList.add("active")}
 pause(){if(this.state!=="play")return;this.state="paused";ui.pause.classList.add("active");ui.pauseButton.hidden=true;music.pause();resetJoystick()}
 resume(){if(this.state!=="paused")return;ui.pause.classList.remove("active");ui.pauseButton.hidden=false;this.state="play";this.last=performance.now();music.play().catch(()=>{})}
 end(){if(this.state!=="play")return;this.state="over";ui.pauseButton.hidden=true;music.pause();const newRecord=this.kills>this.bestKills||this.time>this.bestTime;this.bestKills=Math.max(this.bestKills,this.kills);this.bestTime=Math.max(this.bestTime,this.time);localStorage.setItem("porkBestKills",this.bestKills);localStorage.setItem("porkBestTime",this.bestTime);ui.stats.innerHTML=`<span>Время</span><strong>${formatTime(this.time)}</strong><span>Убито зондби</span><strong>${this.kills}</strong><span>Оружие</span><strong>${weapons[this.weaponLevel].name}</strong><span>Лучший результат</span><strong>${this.bestKills} / ${formatTime(this.bestTime)}</strong>`;ui.record.classList.toggle("show",newRecord);ui.over.classList.add("active");resetJoystick()}
 update(dt){this.time+=dt;if(this.time>=this.nextZombieEffect){zombieEffect.currentTime=0;zombieEffect.play().catch(()=>{});this.nextZombieEffect+=rand(8,16)}this.player.update(dt,this);this.medkitCd-=dt;if(this.medkitCd<=0&&this.medkits.length<2){this.spawnMedkit();if(this.barrels.length<2&&Math.random()<.32)this.spawnBarrel();this.medkitCd=rand(28,44)}for(const m of this.medkits){m.update(dt);if(!m.dead&&hit(m,this.player)){const heal=this.player.maxHp*(m.big?.5:.25);this.player.hp=Math.min(this.player.maxHp,this.player.hp+heal);m.dead=true;for(let i=0;i<14;i++)this.particles.push(new Particle(m.x,m.y,m.big?"#ffdc62":"#f3f0df"))}}this.medkits=this.medkits.filter(m=>!m.dead&&m.life>0);for(const barrel of this.barrels)barrel.update(dt);this.barrels=this.barrels.filter(b=>!b.dead&&b.life>0);this.spawnCd-=dt;const baseInterval=Math.max(.13,.9-this.time*.0032),startRate=.7+.3*clamp(this.time/120,0,1),interval=baseInterval/startRate;if(this.spawnCd<=0&&this.enemies.length<190){this.spawn();if(this.time>90&&Math.random()<.12)this.spawn();if(this.time>210&&Math.random()<.14)this.spawn();this.spawnCd=interval}if(this.time>=this.nextBoss){for(let i=0;i<this.bossWave;i++)this.spawn("boss");this.nextBoss+=180;this.banner=2;this.bannerTitle="ОПАСНОСТЬ";this.bannerText=this.bossWave===1?"БОСС ЗОНДБИ":`${this.bossWave} БОССА ЗОНДБИ`;this.bossWave++}for(const e of this.enemies){e.update(dt,this);if(!e.dead&&hit(e,this.player))this.player.hurt(e.damage,this)}for(const a of this.acidShots){a.update(dt);if(a.life>0&&hit(a,this.player)){a.life=0;this.player.hurt(18,this);for(let i=0;i<10;i++)this.particles.push(new Particle(a.x,a.y,i%2?"#b14cff":"#59246f"))}}for(const b of this.bullets){b.update(dt);for(const e of this.enemies){if(e.dead||b.hitSet.has(e.id)||!hit(b,e))continue;b.hitSet.add(e.id);e.hp-=b.damage;e.flash=.06;for(let i=0;i<4;i++)this.particles.push(new Particle(b.x,b.y,i%3?"#73ff69":"#2f9f43"));if(e.hp<=0)this.kill(e);if(b.pierce<=0){b.life=0;break}b.pierce--}if(b.life>0){for(const barrel of this.barrels){if(barrel.dead||!hit(b,barrel))continue;barrel.hp-=b.damage;b.life=0;if(barrel.hp<=0)this.explodeBarrel(barrel);break}}}this.enemies=this.enemies.filter(e=>!e.dead);this.barrels=this.barrels.filter(b=>!b.dead&&b.life>0);this.bullets=this.bullets.filter(b=>b.life>0&&b.x>-30&&b.x<W+30&&b.y>-30&&b.y<H+30);this.acidShots=this.acidShots.filter(a=>a.life>0&&a.x>-40&&a.x<W+40&&a.y>-40&&a.y<H+40);for(const p of this.particles)p.update(dt);this.particles=this.particles.filter(p=>p.life>0);this.banner=Math.max(0,this.banner-dt);this.shake=Math.max(0,this.shake-dt*18);this.updateDomHud()}
 updateDomHud(){const hp=clamp(this.player.hp/this.player.maxHp,0,1);ui.healthFill.style.width=`${hp*100}%`;ui.healthFill.style.background=hp<.3?"#ff4e45":"#73ff69";ui.healthText.textContent=`${Math.ceil(Math.max(0,this.player.hp))} / ${this.player.maxHp}`;ui.kills.textContent=this.kills;ui.weapon.textContent=weapons[this.weaponLevel].name;ui.next.textContent=this.weaponLevel<weapons.length-1?`СЛЕД.: ${this.weaponKills}/${weaponKillGoals[this.weaponLevel]}`:"МАКСИМУМ";ui.time.textContent=formatTime(this.time)}
 drawBackground(){ctx.fillStyle="#252a2c";ctx.fillRect(0,0,W,H);ctx.fillStyle="#111516";ctx.fillRect(0,0,W,116);ctx.fillStyle="#252c2e";ctx.fillRect(0,8,W,72);ctx.fillStyle="#394144";ctx.fillRect(0,80,W,34);ctx.fillStyle="#101314";ctx.fillRect(0,108,W,8);for(let x=26;x<W;x+=142){ctx.fillStyle="#0c1011";ctx.fillRect(x,18,94,45);ctx.fillStyle="#273235";ctx.fillRect(x+7,24,36,31);ctx.fillRect(x+51,24,36,31);ctx.fillStyle="rgba(115,255,105,.14)";ctx.fillRect(x+10,27,30,5)}ctx.fillStyle="#737d7d";for(let x=8;x<W;x+=105)ctx.fillRect(x,76,72,4);ctx.fillStyle="#e3e6df";ctx.font="900 34px Impact, sans-serif";ctx.textAlign="center";ctx.fillText("З О Н Д Б И   Д А Б А Л А Т О Р И Я",W/2,49);ctx.fillStyle="#73ff69";ctx.font="800 11px monospace";ctx.fillText("СЕКРЕТНЫЙ НАУЧНО-ПРОИЗВОДСТВЕННЫЙ КОМПЛЕКС",W/2,69);ctx.fillStyle="#7b2725";ctx.fillRect(W/2-112,84,224,28);ctx.fillStyle="#15191a";ctx.fillRect(W/2-98,89,196,23);ctx.fillStyle="#ff453d";for(let x=75;x<W;x+=210){ctx.fillRect(x,91,12,8);ctx.globalAlpha=.12;ctx.fillRect(x-18,83,48,25);ctx.globalAlpha=1}ctx.strokeStyle="rgba(215,216,197,.16)";ctx.lineWidth=4;for(let x=40;x<W;x+=170){ctx.beginPath();ctx.moveTo(x,180);ctx.lineTo(x+30,310);ctx.stroke();ctx.beginPath();ctx.moveTo(x+38,520);ctx.lineTo(x+7,680);ctx.stroke()}ctx.strokeStyle="#141819";ctx.lineWidth=2;for(const c of this.cracks){ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(c.x+Math.cos(c.a)*c.l,c.y+Math.sin(c.a)*c.l);ctx.lineTo(c.x+Math.cos(c.a+.7)*c.l*.35,c.y+Math.sin(c.a+.7)*c.l*.35);ctx.stroke()}for(const d of this.debris){ctx.fillStyle=d.c;ctx.fillRect(d.x,d.y,d.w,d.h)}}
 drawObstacle(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.a);ctx.fillStyle="rgba(0,0,0,.35)";ctx.fillRect(-o.w*.48,-o.h*.42,o.w*.98,o.h*.98);ctx.fillStyle="#090b0c";ctx.fillRect(-o.w*.4,-o.h*.62,22,12);ctx.fillRect(o.w*.22,-o.h*.62,22,12);ctx.fillRect(-o.w*.4,o.h*.43,22,12);ctx.fillRect(o.w*.22,o.h*.43,22,12);ctx.fillStyle=o.c;ctx.fillRect(-o.w/2,-o.h/2,o.w,o.h);ctx.fillStyle="#202628";ctx.fillRect(-o.w*.22,-o.h*.39,o.w*.45,o.h*.78);ctx.fillStyle="#0c1214";ctx.fillRect(-o.w*.18,-o.h*.34,o.w*.34,o.h*.25);ctx.fillRect(-o.w*.18,o.h*.1,o.w*.34,o.h*.2);ctx.strokeStyle="#9ca6a5";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-o.w*.16,-o.h*.3);ctx.lineTo(o.w*.16,o.h*.26);ctx.moveTo(o.w*.14,-o.h*.31);ctx.lineTo(-o.w*.1,-o.h*.04);ctx.stroke();ctx.fillStyle="#b5aa78";ctx.fillRect(-o.w*.48,-o.h*.34,7,13);ctx.fillRect(-o.w*.48,o.h*.2,7,13);ctx.fillStyle="#8b2724";ctx.fillRect(o.w*.42,-o.h*.34,7,13);ctx.fillRect(o.w*.42,o.h*.2,7,13);ctx.fillStyle="#252a2c";ctx.fillRect(-o.w*.5,-3,18,8);ctx.fillRect(o.w*.36,-3,18,8);ctx.restore()}
 drawHud(){if(!matchMedia("(pointer: coarse), (max-width: 900px)").matches){ctx.fillStyle="rgba(8,10,11,.82)";ctx.fillRect(18,18,270,72);ctx.fillStyle="#4b2423";ctx.fillRect(31,52,238,20);ctx.fillStyle=this.player.hp/this.player.maxHp<.3?"#ff4e45":"#73ff69";ctx.fillRect(31,52,238*clamp(this.player.hp/this.player.maxHp,0,1),20);ctx.strokeStyle="#aab1ae";ctx.strokeRect(31,52,238,20);ctx.fillStyle="#fff";ctx.font="700 15px monospace";ctx.textAlign="left";ctx.fillText(`HP  ${Math.ceil(Math.max(0,this.player.hp))} / ${this.player.maxHp}`,31,42);ctx.textAlign="center";ctx.font="900 25px Impact, sans-serif";ctx.fillText(`ЗОНДБИ: ${this.kills}`,W/2,42);ctx.font="700 16px monospace";ctx.fillStyle="#b4bcba";ctx.fillText(formatTime(this.time),W/2,67);ctx.textAlign="right";ctx.fillStyle="#73ff69";ctx.font="900 22px Impact, sans-serif";ctx.fillText(weapons[this.weaponLevel].name,W-28,42)}if(this.banner>0){const a=Math.min(1,this.banner*2,(2-this.banner)*4);ctx.globalAlpha=clamp(a,0,1);ctx.fillStyle="rgba(8,10,11,.9)";ctx.fillRect(W/2-330,118,660,88);ctx.textAlign="center";ctx.fillStyle="#73ff69";ctx.font="900 18px monospace";ctx.fillText(this.bannerTitle||"СОБЫТИЕ",W/2,148);ctx.fillStyle="#fff";ctx.font="900 30px Impact, sans-serif";ctx.fillText(this.bannerText,W/2,184);ctx.globalAlpha=1}}
 draw(){ctx.save();if(this.shake)ctx.translate(rand(-this.shake,this.shake),rand(-this.shake,this.shake));this.drawBackground();for(const o of this.obstacles)this.drawObstacle(o);if(this.player){for(const m of this.medkits)m.draw();for(const barrel of this.barrels)barrel.draw();for(const e of this.enemies)e.draw();for(const a of this.acidShots)a.draw();for(const b of this.bullets)b.draw();this.player.draw(this);for(const p of this.particles)p.draw();this.drawHud()}ctx.restore()}
 loop(now){const dt=Math.min(.033,(now-this.last)/1000);this.last=now;if(this.state==="play")this.update(dt);this.draw();requestAnimationFrame(t=>this.loop(t))}
}

const baseStart=Game.prototype.start,baseUpdate=Game.prototype.update,baseDraw=Game.prototype.draw,baseFire=Game.prototype.fire;
Game.prototype.start=function(){baseStart.call(this);this.bonuses=[];this.flames=[];this.bonusCd=rand(40,65);this.shieldTime=0;this.flamethrowerTime=0;this.flameCd=0};
Game.prototype.spawnBonus=function(){for(let tries=0;tries<30;tries++){const x=rand(65,W-65),y=rand(150,H-60),candidate={x,y,w:42,h:42};if(this.obstacles.some(o=>hit(candidate,o))||Math.hypot(x-this.player.x,y-this.player.y)<170)continue;this.bonuses.push(new BonusPickup(Math.random()<.5?"shield":"flame",x,y));return}};
Game.prototype.flameKill=function(e){if(e.dead)return;e.dead=true;this.kills++;for(let i=0;i<(e.type==="boss"?34:10);i++){const p=new Particle(e.x,e.y,i%3?"#ff6828":"#2b211d");p.size*=1.4;this.particles.push(p)}};
Game.prototype.fire=function(w){if(this.flamethrowerTime>0)return;baseFire.call(this,w)};
Game.prototype.update=function(dt){
 if(this.shieldTime>0){this.shieldTime=Math.max(0,this.shieldTime-dt);this.player.invuln=Math.max(this.player.invuln,.12)}
 this.flamethrowerTime=Math.max(0,this.flamethrowerTime-dt);this.bonusCd-=dt;
 if(this.bonusCd<=0&&this.bonuses.length===0){this.spawnBonus();this.bonusCd=rand(40,65)}
 baseUpdate.call(this,dt);
 for(const b of this.bonuses){b.update(dt);if(!b.dead&&hit(b,this.player)){b.dead=true;if(b.type==="shield"){this.shieldTime=20;this.bannerTitle="ВРЕМЕННЫЙ БОНУС";this.bannerText="ЩИТ — 20 СЕКУНД"}else{this.flamethrowerTime=15;this.flameCd=0;this.bannerTitle="ВРЕМЕННЫЙ БОНУС";this.bannerText="ОГНЕМЁТ — 15 СЕКУНД"}this.banner=1.8;for(let i=0;i<20;i++)this.particles.push(new Particle(b.x,b.y,b.type==="shield"?"#67d7ff":"#ff4b35"))}}
 this.bonuses=this.bonuses.filter(b=>!b.dead&&b.life>0);
 if(this.flamethrowerTime>0){this.flameCd-=dt;if(this.flameCd<=0){for(let i=0;i<4;i++)this.flames.push(new FlameParticle(this.player.x+Math.cos(this.player.aim)*28,this.player.y+Math.sin(this.player.aim)*28,this.player.aim));this.flameCd=.075}}
 for(const f of this.flames){f.update(dt);if(f.life<=0)continue;for(const e of this.enemies){if(e.dead||!hit(f,e))continue;f.life=0;this.flameKill(e);break}}
 this.flames=this.flames.filter(f=>f.life>0);
 if(this.flamethrowerTime>0){ui.weapon.textContent=`ОГНЕМЁТ ${Math.ceil(this.flamethrowerTime)}с`;ui.next.textContent=`ОСНОВНОЕ: ${this.weaponKills}/${weaponKillGoals[this.weaponLevel]||"MAX"}`}
};
Game.prototype.draw=function(){baseDraw.call(this);if(!this.player)return;for(const b of this.bonuses)b.draw();for(const f of this.flames)f.draw();if(this.shieldTime>0){const pulse=4+Math.sin(performance.now()*.008)*3;ctx.save();ctx.translate(this.player.x,this.player.y);ctx.strokeStyle="rgba(103,215,255,.85)";ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,35+pulse,0,TAU);ctx.stroke();ctx.strokeStyle="rgba(217,248,255,.28)";ctx.lineWidth=9;ctx.beginPath();ctx.arc(0,0,40+pulse,0,TAU);ctx.stroke();ctx.restore()}ctx.save();ctx.textAlign="center";ctx.font="900 16px monospace";if(this.shieldTime>0){ctx.fillStyle="#9de8ff";ctx.fillText(`ЩИТ ${Math.ceil(this.shieldTime)}с`,W/2,98)}if(this.flamethrowerTime>0){ctx.fillStyle="#ff6b36";ctx.fillText(`ОГНЕМЁТ ${Math.ceil(this.flamethrowerTime)}с`,W/2,this.shieldTime>0?118:98)}ctx.restore()};

const keys={};addEventListener("keydown",e=>{keys[e.code]=true;if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","Space"].includes(e.code))e.preventDefault()});addEventListener("keyup",e=>keys[e.code]=false);addEventListener("blur",()=>{for(const k in keys)keys[k]=false;resetJoystick()});
const joystick={x:0,y:0,pointer:null,baseX:0,baseY:0,max:60},joyEl=document.getElementById("joystick"),joyBase=document.getElementById("joystick-base"),knob=document.getElementById("joystick-knob");
function moveJoystick(e){if(e.pointerId!==joystick.pointer)return;e.preventDefault();const r=joyEl.getBoundingClientRect(),cx=r.left+joystick.baseX,cy=r.top+joystick.baseY;let dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy);if(l>joystick.max){dx=dx/l*joystick.max;dy=dy/l*joystick.max;l=joystick.max}const dead=.1,raw=Math.min(1,l/joystick.max),power=raw<=dead?0:(raw-dead)/(1-dead),nx=l?dx/l:0,ny=l?dy/l:0;joystick.x=nx*power;joystick.y=ny*power;knob.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`}
function resetJoystick(e){if(e&&joystick.pointer!==null&&e.pointerId!==undefined&&e.pointerId!==joystick.pointer)return;joystick.x=joystick.y=0;joystick.pointer=null;joyBase.style.opacity=0;knob.style.opacity=0;knob.style.transform="translate(-50%,-50%)"}
joyEl.addEventListener("pointerdown",e=>{if(game.state!=="play"||joystick.pointer!==null)return;e.preventDefault();const r=joyEl.getBoundingClientRect();joystick.pointer=e.pointerId;joystick.baseX=e.clientX-r.left;joystick.baseY=e.clientY-r.top;joystick.max=Math.max(42,joyBase.getBoundingClientRect().width*.43);for(const el of [joyBase,knob]){el.style.left=`${joystick.baseX}px`;el.style.top=`${joystick.baseY}px`;el.style.opacity=1}try{joyEl.setPointerCapture(e.pointerId)}catch(_){}moveJoystick(e)},{passive:false});
joyEl.addEventListener("pointermove",moveJoystick,{passive:false});
for(const type of ["pointerup","pointercancel","lostpointercapture"])joyEl.addEventListener(type,resetJoystick);
for(const type of ["pointerup","pointercancel"])addEventListener(type,resetJoystick,true);
addEventListener("pagehide",resetJoystick);document.addEventListener("freeze",resetJoystick);
function hideAll(){ui.start.classList.remove("active");ui.upgrade.classList.remove("active");ui.pause.classList.remove("active");ui.over.classList.remove("active")}
const game=new Game();
document.getElementById("start-button").onclick=()=>game.start();document.getElementById("restart-button").onclick=()=>game.start();ui.pauseButton.onclick=()=>game.pause();document.getElementById("resume-button").onclick=()=>game.resume();document.getElementById("menu-button").onclick=()=>{hideAll();ui.start.classList.add("active");ui.pauseButton.hidden=true;music.pause();game.state="menu";game.player=null;game.enemies=[];game.bullets=[];game.particles=[]};
addEventListener("keydown",e=>{if(e.code==="Escape"){if(game.state==="play")game.pause();else if(game.state==="paused")game.resume()}});
document.addEventListener("visibilitychange",()=>{game.last=performance.now();if(document.hidden){resetJoystick();if(game.state==="play")game.pause()}});
for(const event of ["gesturestart","gesturechange","gestureend","dblclick","contextmenu"])document.addEventListener(event,e=>e.preventDefault(),{passive:false});
document.addEventListener("touchmove",e=>e.preventDefault(),{passive:false});
let deferredInstall=null;const installButton=document.getElementById("install-button");
addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;installButton.hidden=false});
installButton.addEventListener("click",async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;installButton.hidden=true});
addEventListener("appinstalled",()=>{installButton.hidden=true;deferredInstall=null});
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
